development:
  adapter: postgresql
  encoding: unicode
  database: lpod_development
  pool: 5
  username: kiwidave
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lpod_test
  pool: 5
  username: kiwidave
  password: 